### ISSUE TITLE
Using "setpropSleep" returns error with exception message

### ISSUE THREAD

**Issue by ZioCain** [picoxr/pico-power-manager#4]
I was trying to use the powermanager API to set the Pico to never sleep, either system or screen, but when I call this API I get the following error message:
`java.lang.NoSuchMethodError: no non-static method with name='setpropSleep' signature='(I)V' in class Ljava.lang.Object;`

The code I use is:

    AndriodJavaObject ajo;
    if(ajo==null){
            ajo = new AndroidJavaObject("com.picovr.picovrpowermanager.PicoVRPowerManager");
            AndroidJavaObject ActivityContext = new AndroidJavaClass("com.unity3d.player.UnityPlayer").GetStatic<AndroidJavaObject>("currentActivity");
            ajo.Call("init", ActivityContext);
        }
        try{
            ajo.Call("setpropSleep", 1800);
            ajo.Call("setPropLockScreen", 1800);
        }catch(AndroidJavaException e){
            // Error("Error during setting sleepTime");
            print("sleepTime error: "+e.Message);
            return;
        }catch(System.Exception e){
            // Error("sleepTime error");
            print("sleepTime exception: "+e.Message);
            return;
        }
    }

In my `Assets/Plugins/Android` folder I have:
- AndroidManifest.xml
- android-support-v4.jar
- Pico_PaymentSDK_Android_V.1.0.24.jar
- powermanager.jar (downloaded from one of your repos)
- vractivity.jar
- zip_file.jar
- other stuff coming from other plugins

Is there a problem in the name or something should be updated?

**Comment by dragongyke** [comment]
Hi ZioCain, according to the codes the input value type for the intercaces is string, so the code should be "ajo.Call("setpropSleep", "1800");", please have a try.

**Comment by ZioCain** [comment]
Yeah it works like that! Thank you!
