### ISSUE TITLE
"goToApp" doing nothing (probably using it the wrong way)

### ISSUE THREAD

**Issue by ZioCain** [picoxr/pico-power-manager#5]
Hello, I was trying to put a button that allows me to open pico's file manager.
What I'm currently using in my code is:
```
ajo = new AndroidJavaObject("com.picovr.picovrpowermanager.PicoVRPowerManager");
AndroidJavaObject ActivityContext = new AndroidJavaClass("com.unity3d.player.UnityPlayer").GetStatic<AndroidJavaObject>("currentActivity");
ajo.Call("init", ActivityContext);
ajo.Call("goToApp", "com.picovr.filemanager" ); // got the name from the folder in Android/data
```

When I run tis code, I don't get any error, but nothing happens, I tried to switch to other apps but none works, therefore it must be something in my code, can I get a little help?

Extra details:
- Pico G2 base version
- Latest PUI version 3.6.0
- App runs in kiosk mode and has system signature (other features requiring SysSig work)

**Comment by picoxr** [comment]
Hi,
In PUI version 3.6.0, the package name of file manager have changed to "com.pvr.filemanager". If you have any question, feel free to contacte us.

**Comment by ZioCain** [comment]
Ok I finally managed to try it and it works 100%, thank you very much!
