### ISSUE TITLE
Is there a way to have an error message or something when a call doesn't go as expected?

### ISSUE THREAD

**Issue by ZioCain** [picoxr/pico-power-manager#6]
I've been trying to use the `silentInstall` function to install an APK an it just didn't work.
I then realized it was because the version of the APK I was trying to install was lower than the one of the APK already installed.
An error message like the one I get from the `adb` command line would be great.

**Comment by dragongyke** [comment]
Hi, we have updated the codes and jar file. Now you can see the error message in logs when the installation failed.
