### ISSUE TITLE
acquireWakeLock example?

### ISSUE THREAD

**Issue by Adeptus-Astartes** [picoxr/pico-power-manager#7]
I tried  PowerManager.Call("acquireWakeLock", (object)null); but it doesn't work

**Comment by picoxr** [comment]
Did you add <uses-permission android:name="android.permission.WAKE_LOCK" /> permission in your AndroidManifest.xml?
And this repo is deprecated, pls use https://github.com/picoxr/AndroidHelper, it has added required permissions in the .aar file.

If it still doesn't work, could you share your code and your testing method?
